import jsPDF from "jspdf";
import JSZip from "jszip";
import { supabase } from "@/integrations/supabase/looseClient";
import { ensureChannelReport } from "./channelReport";

export interface ReportLead {
  channelLink: string;
  channelName?: string;
  extra?: Record<string, any>;
}

const fmt = (n: any) => (n === null || n === undefined || n === "" ? "-" : Number(n).toLocaleString());

/** Builds a one-page PDF report for a channel. */
async function buildChannelPdf(lead: ReportLead): Promise<{ name: string; blob: Blob }> {
  const url = lead.channelLink.trim();
  const { data: yt, error } = await supabase.functions.invoke("youtube-channel-info", {
    body: { channelUrl: url, includeVideos: true },
  });
  if (error || yt?.error) throw new Error(yt?.error || error?.message || "Failed to fetch channel");

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  let y = 60;

  doc.setFillColor(234, 88, 12); // orange accent
  doc.rect(0, 0, W, 6, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text(yt.channelName || lead.channelName || "Channel Report", 40, y); y += 22;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(yt.customUrl || url, 40, y); y += 26;

  doc.setTextColor(0);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.text("Channel Stats", 40, y); y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  const stats: [string, string][] = [
    ["Subscribers", fmt(yt.subscribers)],
    ["Total Views", fmt(yt.totalViews)],
    ["Videos", fmt(yt.videoCount)],
    ["Country", yt.country || "-"],
  ];
  for (const [k, v] of stats) { doc.text(`${k}:  ${v}`, 40, y); y += 15; }
  y += 10;

  if (yt.description) {
    doc.setFont("helvetica", "bold"); doc.setFontSize(13);
    doc.text("About", 40, y); y += 16;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    const lines = doc.splitTextToSize(String(yt.description).slice(0, 900), W - 80);
    doc.text(lines, 40, y); y += lines.length * 13 + 12;
  }

  const vids = (yt.videos || yt.recentVideos || []).slice(0, 8);
  if (vids.length) {
    if (y > 700) { doc.addPage(); y = 60; }
    doc.setFont("helvetica", "bold"); doc.setFontSize(13);
    doc.text("Recent Videos", 40, y); y += 16;
    doc.setFont("helvetica", "normal"); doc.setFontSize(10);
    for (const v of vids) {
      if (y > 780) { doc.addPage(); y = 60; }
      const title = String(v.title || "").slice(0, 90);
      doc.text(`• ${title}`, 40, y); y += 14;
    }
  }

  doc.setFontSize(8); doc.setTextColor(140);
  doc.text(`Generated by SwishView · ${new Date().toLocaleDateString()}`, 40, 820);

  const safe = (yt.channelName || lead.channelName || "channel").replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").slice(0, 50);
  return { name: `${safe || "channel"}-report.pdf`, blob: doc.output("blob") };
}

const escapeCsv = (v: any) => {
  const s = v === null || v === undefined ? "" : String(v).replace(/\r?\n/g, " ");
  return /[",\n]/.test(s) ? '"' + s.replace(/"/g, '""') + '"' : s;
};

function downloadBlob(blob: Blob, filename: string) {
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 5000);
}

/**
 * Generates real PDF reports for the given leads, downloads them as a ZIP,
 * plus a CSV sheet whose "Report PDF" column names the attached PDF file.
 * Also saves each report to the database (via ensureChannelReport).
 */
export async function downloadLeadReportsZip(
  leads: ReportLead[],
  sheetColumns: { header: string; value: (l: ReportLead) => any }[],
  baseName: string,
  onProgress?: (msg: string) => void,
) {
  const zip = new JSZip();
  const pdfNames = new Map<string, string>();
  let done = 0, failed = 0;
  let idx = 0;
  const worker = async () => {
    while (idx < leads.length) {
      const lead = leads[idx++];
      const link = lead.channelLink.trim();
      if (!link) { failed++; continue; }
      try {
        await ensureChannelReport(link); // persist to DB
        const pdf = await buildChannelPdf(lead);
        let name = pdf.name, n = 1;
        while (zip.file(name)) name = pdf.name.replace(/\.pdf$/, `-${++n}.pdf`);
        zip.file(name, pdf.blob);
        pdfNames.set(link, name);
      } catch { failed++; }
      onProgress?.(`PDF ${++done}/${leads.length}`);
    }
  };
  await Promise.all(Array.from({ length: 3 }, worker));

  if (pdfNames.size === 0) throw new Error("No PDF reports could be generated");

  onProgress?.("Zipping…");
  const zipBlob = await zip.generateAsync({ type: "blob" });
  const date = new Date().toISOString().slice(0, 10);
  downloadBlob(zipBlob, `${baseName}-reports-${date}.zip`);

  const header = [...sheetColumns.map(c => c.header), "Report PDF"];
  const lines = [header, ...leads.map(l => [
    ...sheetColumns.map(c => c.value(l)),
    pdfNames.get(l.channelLink.trim()) || "",
  ])].map(r => r.map(escapeCsv).join(","));
  downloadBlob(new Blob(["\uFEFF" + lines.join("\n")], { type: "text/csv;charset=utf-8" }), `${baseName}-reports-${date}.csv`);

  return { made: pdfNames.size, failed };
}
