// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cunwojfroszzwznvmelt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1bndvamZyb3N6end6bnZtZWx0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4NzM5NzIsImV4cCI6MjA2NTQ0OTk3Mn0.VLx2_l4CGq7KQoZzeCC8nerehWMAta0ecOLTVEcwIo0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);